### ISSUE TITLE
Cannot run test --watch

### ISSUE THREAD

**Issue by samthui** [ferrannp/react-native-testing-example#4]
I've cloned sample source code and run ```npm test``` successfully  (some pass, some fail).
But running ```npm test -- --watch``` shows error 

`Determining test suites to run...Error: This promise must be present when running with -o.
    at /Users/smisy/Downloads/Source Codes/React Native/react-native-testing-example-master/node_modules/jest/node_modules/jest-cli/build/search_source.js:202:17
    at Generator.next (<anonymous>)
    at step (/Users/smisy/Downloads/Source Codes/React Native/react-native-testing-example-master/node_modules/jest/node_modules/jest-cli/build/search_source.js:19:362)
    at /Users/smisy/Downloads/Source Codes/React Native/react-native-testing-example-master/node_modules/jest/node_modules/jest-cli/build/search_source.js:19:592
    at Promise (<anonymous>)
    at /Users/smisy/Downloads/Source Codes/React Native/react-native-testing-example-master/node_modules/jest/node_modules/jest-cli/build/search_source.js:19:273
    at SearchSource.getTestPaths (/Users/smisy/Downloads/Source Codes/React Native/react-native-testing-example-master/node_modules/jest/node_modules/jest-cli/build/search_source.js:216:10)
    at /Users/smisy/Downloads/Source Codes/React Native/react-native-testing-example-master/node_modules/jest/node_modules/jest-cli/build/run_jest.js:44:29
    at Generator.next (<anonymous>)
    at step (/Users/smisy/Downloads/Source Codes/React Native/react-native-testing-example-master/node_modules/jest/node_modules/jest-cli/build/run_jest.js:23:380)`

What does it mean? And how to solve it?

**Comment by ferrannp** [comment]
It seems a dependency problem to me. I just cloned the repo freshly and `watch` works for me. Make sure to use yarn:

```js
git clone https://github.com/ferrannp/react-native-testing-example.git
yarn
yarn test --watch
```
